travis-ci: fix OS-X/Mac issues, which builds in two directories 	   make work outside travis-ci, to make debug easier 	   fail if zero things deploy
Signed-off-by: Robin Getz <robin.getz@analog.com>

diff --git a/CI/travis/before_deploy b/CI/travis/before_deploy
--- a/CI/travis/before_deploy
+++ b/CI/travis/before_deploy
@@ -1,47 +1,93 @@
 #!/bin/sh
 
-cd $TRAVIS_BUILD_DIR
+# Don't prepare a deploy on a Coverity build
+if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi
+
+deploy=0
+if [ -z "$TRAVIS_BUILD_DIR" ] ; then
+	t=$(find ./ -name CMakeCache.txt|head -1)
+	if [ -n "${t}" ] ; then
+		cd $(dirname $(dirname ${t}))
+		TRAVIS_BUILD_DIR=$(pwd)
+	else
+		echo "I am confused - can't find CMakeCache.txt"
+		exit
+	fi
+else
+	cd $TRAVIS_BUILD_DIR
+fi
+pwd
+
+if [ -z "${LDIST}" ] ; then
+	LDIST=-$(lsb_release -c | awk '{print $NF}')
+fi
 
 check_file()
 {
-temp=$(find ./build* -maxdepth 1 -name "*.$1")
-if [ "$(echo ${temp} | wc -w)" -gt "1"  ] ; then
-	echo "I am confused - more than 2 $1 files"
-	echo $temp
-	exit
+temp=""
+for i in $(find ./ -name CMakeCache.txt)
+do
+hit=$(find $(dirname ${i}) -maxdepth 1 -name "libiio*.$1")
+if [ "$(echo ${hit} | wc -w)" -gt "1"  ] ; then
+	echo "I am confused - more than 2 $1 files!"
+	echo $hit
+	exit 1
+else
+	if [ "$(echo ${hit} | wc -w)" -eq "1" ] ; then
+		if [ -z "${temp}" ] ; then
+			temp=$hit
+		else
+			echo "I am confused - more than 2 $1 files"
+			echo $temp
+			echo $hit
+			exit 1
+		fi
+	fi
 fi
+done
 }
 
 check_file deb
 if [ -n "${temp}" ] ; then
+	deploy=$(expr ${deploy} + 1)
 	export TARGET_DEB=$(echo ${temp} | \
 		sed -e 's:^./.*/::' -e 's:.deb$::')${LDIST}.deb
 	echo "deploying ${temp} to nightly $TARGET_DEB"
-	cp ${temp} ${TARGET_DEB}
-	export RELEASE_PKG_FILE_DEB=./build/${TARGET_DEB}
+	export RELEASE_PKG_FILE_DEB=$(dirname ${temp})/${TARGET_DEB}
+	cp ${temp} ${RELEASE_PKG_FILE_DEB}
+	echo ${TARGET_DEB}
 	ls -lh ${temp}
+	echo ${RELEASE_PKG_FILE_DEB}
+	ls -lh ${RELEASE_PKG_FILE_DEB}
 else
 	echo "Skipping deployment of debian package"
 fi
 
 check_file rpm
 if [ -n "${temp}" ] ; then
+	deploy=$(expr ${deploy} + 1)
 	export TARGET_RPM=$(echo ${temp} | \
 		sed -e 's:^./.*/::' -e 's:.rpm$::')${LDIST}.rpm
 	echo "deploying ${temp} to nightly $TARGET_RPM"
-	cp ${temp} ${TARGET_RPM}
-	export RELEASE_PKG_FILE_RPM=./build/${TARGET_RPM}
+	export RELEASE_PKG_FILE_RPM=$(dirname ${temp})/${TARGET_RPM}
+	cp ${temp}  ${RELEASE_PKG_FILE_RPM}
+	echo ${TARGET_RPM}
 	ls -lh ${temp}
+	echo ${RELEASE_PKG_FILE_RPM}
+	ls -lh ${RELEASE_PKG_FILE_RPM}
 else
 	echo "Skipping deployment of rpm package"
 fi
 
 check_file tar.gz
 if [  -n "${temp}"  ] ; then
+	deploy=$(expr ${deploy} + 1)
 	# Add the MATLAB bindings into the tar file
 	(
 		cd $(dirname ${temp})
-
+		if [ -d tarball_fixup ] ; then
+			rm -rf tarball_fixup
+		fi
 		mkdir tarball_fixup && cd tarball_fixup
 
 		if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
@@ -84,22 +130,33 @@ if [  -n "${temp}"  ] ; then
 	export TARGET_TGZ=$(echo ${temp} | \
 		sed -e 's:^./.*/::' -e 's:.tar.gz$::')${LDIST}.tar.gz;
 	echo "deploying ${temp} to $TARGET_TGZ"
-	cp ${temp} ${TARGET_TGZ}
-	export RELEASE_PKG_FILE_TGZ=./build/${TARGET_TGZ}
+	export RELEASE_PKG_FILE_TGZ=$(dirname ${temp})/${TARGET_TGZ}
+	cp ${temp} ${RELEASE_PKG_FILE_TGZ}
+	echo ${TARGET_TGZ}
 	ls -lh ${temp}
+	echo ${RELEASE_PKG_FILE_TGZ}
+	ls -lh ${RELEASE_PKG_FILE_TGZ}
 else
 	echo "Skipping deployment of tarball"
 fi
 
 check_file pkg
 if [ -n "${temp}" ] ; then
+	deploy=$(expr ${deploy} + 1)
 	export TARGET_PKG=$(echo ${temp} | \
 		sed -e 's:^./.*/::' -e 's:.pkg$::')${LDIST}.pkg
 	echo "deploying ${temp} to nightly $TARGET_PKG"
-	cp ${temp} ${TARGET_PKG}
-	export RELEASE_PKG_FILE_PKG=./build/${TARGET_PKG}
+	export RELEASE_PKG_FILE_PKG=$(dirname ${temp})/${TARGET_PKG}
+	cp ${temp} ${RELEASE_PKG_FILE_PKG}
+	echo ${TARGET_PKG}
 	ls -lh ${temp}
+	echo ${RELEASE_PKG_FILE_PKG}
+	ls -lh ${RELEASE_PKG_FILE_PKG}
 else
 	echo "Skipping deployment of OS X package"
 fi
 
+if [ "${deploy}" -eq "0" ] ; then
+	echo did not deploy any files
+	exit 1
+fi
